version: '1.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: Prueba  
      MYSQL_USER: rivasj 
      MYSQL_PASSWORD: julian123 
      MYSQL_ROOT_PASSWORD: rootpassword 
    ports:
      - "3306:3306" 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80" 
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword 
